name: CI
on:
  - pull_request
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'adopt'
      - name: Set executable permission for gradlew
        working-directory: rentalService
        run: chmod +x gradlew
      - name: Build and test
        working-directory: rentalService
        run: |
          export SHELL=/bin/bash
          ./gradlew build
      - name: Docker images
        working-directory: rentalService
        run: |
          export SHELL=/bin/bash
          docker buildx build -t rentalservice .
          docker images

